# Generated by Django 3.2.3 on 2021-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='Login', max_length=255, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='Name', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='SerName', max_length=255, verbose_name='Фамилия'),
        ),
    ]
