# Generated by Django 3.2.3 on 2021-08-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0002_auto_20210730_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_carts', to='green.Green'),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
