# Generated by Django 3.2.3 on 2021-08-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0005_auto_20210812_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_carts', through='green.CartLineItem', to='green.Green'),
        ),
    ]
