# Generated by Django 3.2.3 on 2021-08-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0006_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='green',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Наличие'),
        ),
    ]
