# Generated by Django 3.2.3 on 2021-08-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0007_green_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartlineitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartlineitem',
            name='green',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartLineItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
